spring.application.name=roonie
server.port=8090
spring.main.web-application-type=servlet

roonie.token=${ROONIE_BOT_TOKEN}
roonie.path=${MEDIA_PATH}

splayfunity.mainGuild=873506353551925308
splayfunity.emojiServerGuild=877158057988202496
splayfunity.emojiServerGuild2=879786460667052083
splayfunity.autoroles=891292965241233448

mongo.host=${MONGO_HOST}
mongo.username=${MONGO_USERNAME}
mongo.password=${MONGO_PASSWORD}